baseURL = "/"
languageCode = "en-us"
theme = "albatrans-theme"
title = "AlbaTrans sh.p.k."
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4
[[menu.main]]
name = "Informacion i pergjithshem"
url = "/testimonials/"
weight = 3
[[menu.main]]
name = "Team"
url = "/team/"
weight = 2
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1
[params]
google_analytics_id = "UA-141803043-1"
[params.homepage_meta_tags]
meta_description = "AlbaTrans offers some of the most versatile and efficient transport services for its passengers."
meta_og_description = "AlbaTrans offers some of the most versatile and efficient transport services for its passengers."
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "AlbaTrans sh.p.k."
meta_og_type = "website"
meta_og_url = "http://albatrans.al"
meta_twitter_card = "summary"
meta_twitter_creator = "@oerd"
meta_twitter_site = "@infotourist"
